### ISSUE TITLE
RARS 'loosing' some of its RISC-V commands in certain circumstances

### ISSUE THREAD

**Issue by martinberger** [TheThirdOne/rars#65] opened 2019-12-05 20:48 UTC
My compiler students report a strange problem with RARS. I'm almost certain that this is a problem in our labs, but it's sufficiently surprising that you may be interested in it, at least it shows that RARS is not robust under a certain kind of failure (we never had this problem with MARS). The problem is this: When downloading RARS to the Windows machines in out lab: 

- RARS runs fine from the C drive directories. 
- If RARS is moved onto the N drive (which is most common to students, as this is where their documents and desktop are stored- so they can be accessed by any of the labs) it no longer functions properly. The jar file still opens but has a **reduced instruction set**!

Compare the following:
   - Instruction set when typing `beq` when opened from the C drive, see [1].
   - Instruction set when opened from the N drive, see [2]. As you can see the instruction `beq` is missing! When  trying to run this function the error [3] appears. When using instructions it does recognise and assembling the code, it never moves onto the next screen so that it can be run, however it is also not frozen as the output box can be cleared and new instructions typed. Basically it doesn't run any of the functionality it is meant to have. Note the code can be saved in the N file the only thing that makes a difference is where the .jar file is located. Maybe RARS tries to load some classes/libraries that it cannot access but it fails silently.

**Note**: this problem only occurs on the Windows machines in our lab, not on personal Macs, Linux and Windows machines, where it runs without issue.

1. http://users.sussex.ac.uk/~mfb21/compilers/rars1.png 
2. http://users.sussex.ac.uk/~mfb21/compilers/rars2.png
3. http://users.sussex.ac.uk/~mfb21/compilers/rars3.png

**Comment by TheThirdOne** [comment] 2019-12-06 04:11
I suspect that the instructions that are available are all psuedo-instructions and the ones that are not  present are real instructions. All real instructions are dynamically loaded from class files within the jar so something must be going wrong with that.

I would have to get a Windows machine set up to debug this as I normally run Linux. There isn't very much code that handles the loading, so it should be possible for a student to debug this if they want to. I will try to get to this soon though.

The relevant code is: 
https://github.com/TheThirdOne/rars/blob/287f2fb4eddf160f070bffcb6a29fff83c316be9/src/rars/riscv/InstructionSet.java#L129-L157

**Comment by TheThirdOne** [comment] 2019-12-06 06:57
With Windows 10, Java 8 and a flash drive I can't reproduce this issue. I added a debug statement in the instruction. Please run this and look at System.out. 

[rars.zip](https://github.com/TheThirdOne/rars/files/3930781/rars.zip)

**Comment by martinberger** [comment] 2019-12-13 22:45
We've tried the annotated version of RARS in the zip file yesterday. We did not see any debug output. But we notices two things.

1. The problem only arises when RARS is opened by double clicking. It doesn't arise if we open RARS from the command line, even on the drive we thought caused the problem.

2. If RARS is started by double clicking, then pressing the Help button crashes the program.

Maybe that is of help.

**Comment by TheThirdOne** [comment] 2019-12-14 01:38
Hmm, it should have definitely logged something to standard out. I think that if it only appears when double clicking in  a different drive it must have something to do with the classpath being messed up. 

Could you tell me what Windows and Java version the affected systems are on? 

Having a better logging system to help find issues like this has been on my mind. However, I don't know enough about how Java works on different OSs to write error logging that would work cross platform.

**Comment by TheThirdOne** [comment] 2020-09-29 05:02
@martinberger, has this issue been seen again at all? If it hasn't, I am going to close this because I can't reproduce it.

**Comment by martinberger** [comment] 2020-09-29 07:39
Hello Benjamin, I've not used RARS since I finished teaching in January.
Feel free to close. -- Martin

**Closed** 2020-09-29 09:18 UTC
Labels: help wanted
