### ISSUE TITLE
auipc issue

### ISSUE THREAD

**Issue by mvlamar** [TheThirdOne/rars#6] opened 2018-05-03 22:39 UTC
Please, just confirm that in Rars
auipc t0,imm 
is loading t0 = PC+4 + Imm<<12   instead   t0 =PC + Imm<<12  
I tried to fix it in the definition file [AUIPC.java](https://github.com/TheThirdOne/rars/blob/master/rars/riscv/instructions/AUIPC.java) but I suppose the problem is a little bit deeper, right?

By the way, congratulations for this project! That is just what we were waiting for adopt RISC-V in our undergraduate courses([UnB](http://www.cic.unb.br/))! So, maybe from now you will receive a lot of suggestions... :)

**Comment by TheThirdOne** [comment] 2018-05-04 05:33
It seems like this is a bug in RARS. AUIPC is one of the instructions that is not tested by spike's tests so it may have incorrect behavior.

RARS increments PC before executing instructions so I believe that there should be a `- instruction length` in the code for AUIPC. 

I'll try to setup the tests to verify that it is actually a bug in the next week, and if it is fix it. It would be a very simple fix.

**Comment by TheThirdOne** [comment] 2018-05-04 06:17
The tests from https://github.com/riscv/riscv-tests were not directly convertible so I just confirmed that is is setting PC+4 and added the fix.  

Thanks for the report.

**Comment by mvlamar** [comment] 2018-05-04 21:10
As I said... it is not that simple. I did try to subtract 4 from PC in AUIPC.java file.
Doing it, all pseudoinstructions that uses auipc will get wrong (la, call, tail, lw, lh, etc.), because all of them assumes PC+4 to calculate the immediate.
Example: pseudo la (load address) which uses PCH2 and PCL2 as arguments to create auipc and addi, does not work correctly because PCL2 is wrong!
Try to run the code:

.text
                 nop
                 la x5,ADDRESS
                 nop
                 nop
ADDRESS:  nop
                 nop

which is assembled to
0x00400000 0x00000013  addi x0,x0,0x00000000      // (yes, I modified nop to a pseudo to correct it)
0x00400004 0x00000297  auipc x5,0x00000000        // now it is Ok!!  x5=0x00400004
0x00400008 0x00c28293  addi x5,x5,0x0000000c      // however this imm is wrong now !
0x0040000c 0x00000013  addi x0,x0,0x00000000
0x00400010 0x00000013  addi x0,x0,0x00000000
0x00400014 0x00000013  addi x0,x0,0x00000000     //  <<<< here is ADDRESS
0x00400018 0x00000013  addi x0,x0,0x00000000

x5 must be set to 0x00400014, but it is 0x00400010.
So, I think that the solution for auipc bug is not simply to put -4 in AUIPC.java code. It is better return auipc to original code, while try another way to fix it.

**Comment by TheThirdOne** [comment] 2018-05-04 22:11
`auipc` had the wrong behavior when used in isolation so I stand by correcting it.  

However it appears I incorrectly implemented something with the psuedo-ops aswell. 

I think the problem is that `PCL` and `PCH` are both relative to the actually instruction using them rather than the first instruction of the psuedo-op that generated them. This would make `la` be behind by 1 instruction.

So when `PCL` and `PCH` are used with multi-line psuedo-ops they have an odd behavior, but I wouldn't call them incorrect. 

My first thought on the best way to fix `la` and friends is to make `PCL` and `PCH` relative to the first psuedo-op, but if that is unreasonably hard, adding a `addi RG1, RG1, 4` would be the correct way to fix this within the psuedo-op definitions.

**Comment by TheThirdOne** [comment] 2018-05-04 22:26
Ok, this is actually a pretty easy fix. Rather than get the PC for every psuedo-op as in the [current code](https://github.com/TheThirdOne/rars/blob/ac339c751bc8ffaddad390f5fb5b5c939bb2cf51/rars/assembler/Assembler.java#L248), if it is saved once before the loop it should make `PCL` and `PCH` pseudo-op relative rather than instruction relative. I have tested that this makes `la` work again.

I think that is the most sensible way for them to work. I'll update the comments to reflect the new behavior and commit the fix.

**Comment by TheThirdOne** [comment] 2018-05-04 23:11
Ok, I've committed the pseudo-op fix.

**Closed** 2018-05-07 15:54 UTC

**Comment by mvlamar** [comment] 2018-05-09 23:34
Thanks!
