### ISSUE TITLE
Blue screen after executing my code

### ISSUE THREAD

**Issue by florianMaz** [TheThirdOne/rars#34] opened 2019-06-05 14:37 UTC
OS : MAC Mojave 10.14.4
JAVA version : "11.0.1" 2018-10-16 LTS

I got a blue screen after running my code : 

<img width="1440" alt="Capture d’écran 2019-06-05 à 09 23 51" src="https://user-images.githubusercontent.com/33174816/58964574-709ee980-87af-11e9-8f64-e1d1c92acaad.png">

**Comment by TheThirdOne** [comment] 2019-06-05 17:39
To you have a repeatable way to reproduce this issue? I won't be able to track down what could cause the issue without one.

**Comment by florianMaz** [comment] 2019-06-05 17:50
Yes of course, i just load an asm file.
Just a simple code which display "Hello world"

**Comment by TheThirdOne** [comment] 2019-06-05 18:06
Have you tried using a Windows or Linux machine? I am assuming this is a Mac specific problem.

I don't have access to a Mac at the moment, but I should be able to find one in a week to try to find what is causing this.

**Comment by florianMaz** [comment] 2019-06-05 18:08
Yes i tried and it's works fine on a windows.

**Comment by TheThirdOne** [comment] 2019-06-17 18:03
I got a chance to test this out, and couldn't reproduce the issue. However I think I understand what makes Macs different. I think the windows are just squished so you can't see the text or data segment windows. If you can interact with the top of the windows from your screenshot, that would help confirm this.

Given that I haven't been able to reproduce this, I'm going to close the issue until a more detailed way to reproduce is provided. If you can narrow down the issue so I can reproduce it, then I will try to fix it.

 I tested with Java 8 u211 and Java 12. It is possible this is a Java 11 issue. Changing Java versions may make the issue disappear. Also, if you can, please try a different Mac and see if you still experience the same issue.

Also it may be helpful to post a log from `java -jar rars.jar` run in Terminal. If this is the result of a null dereference, then that should show up in the log.

**Closed by TheThirdOne** 2019-06-17 18:03 UTC
Labels: bug, help wanted

**Comment by Tristan1075** [comment] 2020-05-05 13:44
Hello, same problem here just running an example project :/

OS : Catalina 10.15.3
JAVA version : openjdk 14.0.1 2020-04-14
Rars 1.4

**Comment by TheThirdOne** [comment] 2020-05-06 04:37
@Tristan1075, I still cannot reproduce this issue. I just tried with openjdk 14.0.1, and Mojave 10.14.9.

If you can give me a log that shows something going wrong, I can probably fix this, but without more information I cannot do anything.

**Comment by dionisllupo** [comment] 2024-02-03 22:26
I am having the same issue

**Comment by RomanJ0nes** [comment] 2025-02-12 23:15
I had run into the same issue but I have found a fix for it. Though I don't understand what causes it, the steps to get rid of it are:
-> Open your file on RARS but do not assemble it yet. Do not open the execute tab either
-> Pull down the slider so that the edit section becomes larger
-> Then assemble the file and now you should be able to open the execute tab.

Hope this helps
