### ISSUE TITLE
Error with I type instructions

### ISSUE THREAD

**Issue by ziul123** [TheThirdOne/rars#134] opened 2021-09-30 14:36 UTC
Trying to assemble the instruction `addi t0, t0, 0xEEE` results in an `operand is out of range` error, even though the number 0xEEE has 12 bits, therefore complying with the RISC-V specs for I type instructions.

![image](https://user-images.githubusercontent.com/37045052/135475412-45a4f91b-ff9a-43fc-8ec5-76612dce1e8c.png)

**Comment by TheThirdOne** [comment] 2021-09-30 21:14
This is a duplicate of #103 and #5.

TLDR: Write the sign-extended value. `addi t0, t0, 0x00000EEE` is not a possible instruction so RARS rejects it.

**Closed by TheThirdOne** 2021-09-30 21:14 UTC
